on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

name: 'Rust'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        include:
          - toolchain: stable
          - toolchain: nightly
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: 'Setup Rust'
        run: |
          curl -sSf https://sh.rustup.rs | sh -s -- -y
          rustup toolchain install ${{matrix.toolchain}}
      - name: 'Build'
        run: cargo +${{matrix.toolchain}} build --release
      - uses: actions/upload-artifact@v4
        with:
          name: runtime-${{matrix.toolchain}}
          path: target/release/rust_ci_labs

  release:
    name: Release
    needs: ["build"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/edge',
              sha: context.sha
            })
      - uses: actions/download-artifact@v4
        with:
          pattern: runtime-*
          path: release-artifacts/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: edge
          body: "Latest commit: ${{ github.event.head_commit.message }}"
          draft: true
          files: |
            release-artifacts/runtime-stable
            release-artifacts/runtime-nightly

