on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

name: 'Rust'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        include:
          - toolchain: stable
          - toolchain: nightly
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: 'Setup Rust'
        run: |
          curl -sSf https://sh.rustup.rs | sh -s -- -y
          rustup toolchain install ${{matrix.toolchain}}
      - name: 'Build'
        run: cargo +${{matrix.toolchain}} build --release
      - uses: actions/upload-artifact@v4
        with:
          name: runtime-${{matrix.toolchain}}
          path: target/release/rust_ci_labs

  release:
    name: Release
    needs: ["build"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: runtime-*
          path: release-artifacts/
      - name: Display structure of downloaded files
        run: ls -R release-artifacts/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-artifacts/*
          draft: true

