on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

name: 'Rust'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        include:
          - toolchain: stable
          - toolchain: nightly
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: 'Setup Rust'
        run: |
          curl -sSf https://sh.rustup.rs | sh -s -- -y
          rustup toolchain install ${{matrix.toolchain}}
      - name: 'Build'
        run: cargo +${{matrix.toolchain}} build --release
      - uses: actions/upload-artifact@v3
        with:
          name: runtime
          path: target/release/rust_ci_labs

